name: Terraform Deployment

on:
  push:
    branches:
      - main
      - feature/*

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Lê o arquivo terraform-config.yml e extrai o valor de "destroy"
      - name: Parse terraform-config.yml
        id: parse_config
        run: |
          # Se tiver "yq" instalado no runner, pode usar:
          # DESTROY_VALUE=$(yq e '.destroy' terraform-config.yml)
          # Ou faz um parse manual via grep/awk:
          DESTROY_VALUE=$(grep '^destroy:' terraform-config.yml | awk '{print $2}')
          echo "Valor lido de destroy: $DESTROY_VALUE"
          echo "DESTROY=$DESTROY_VALUE" >> $GITHUB_ENV

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6

      - name: Ensure S3 Backend Exists
        run: |
          BUCKET_NAME="terraform-state-bucket-devair"
          REGION="us-east-1"
          if ! aws s3api head-bucket --bucket "$BUCKET_NAME" 2>/dev/null; then
            echo "Bucket does not exist. Creating..."
            aws s3api create-bucket --bucket "$BUCKET_NAME" --region "$REGION" \
              --create-bucket-configuration LocationConstraint="$REGION"
            echo "Bucket created: $BUCKET_NAME"
          else
            echo "Bucket already exists: $BUCKET_NAME"
          fi
          # Habilita versionamento no bucket
          aws s3api put-bucket-versioning --bucket "$BUCKET_NAME" \
            --versioning-configuration Status=Enabled

      - name: Terraform Init with Remote State
        run: |
          terraform init \
            -backend-config="bucket=terraform-state-bucket-devair" \
            -backend-config="key=terraform.tfstate" \
            -backend-config="region=us-east-1"

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        # Só roda se a variável DESTROY != 'true'
        if: ${{ env.DESTROY != 'true' }}
        run: terraform apply -auto-approve

      - name: Terraform Destroy
        # Só roda se a variável DESTROY == 'true'
        if: ${{ env.DESTROY == 'true' }}
        run: terraform destroy -auto-approve
