name: Terraform Deployment

on:
  push:
    branches:
      - feature/*

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6

      - name: Read configuration
        id: read-config
        run: |
          CONFIG_FILE="terraform-config.yml"
          if [ -f "$CONFIG_FILE" ]; then
            echo "Reading configuration file..."
            DESTROY=$(cat $CONFIG_FILE | grep 'destroy:' | awk '{print $2}')
          else
            echo "No configuration file found. Using defaults."
            DESTROY=false
          fi
          echo "destroy=$DESTROY" >> $GITHUB_ENV

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        if: env.destroy != 'true'
        run: terraform apply -auto-approve

      - name: Terraform Destroy
        if: env.destroy == 'true'
        run: terraform destroy -auto-approve
