name: Terraform Deployment

on:
  push:
    branches:
      - main
      - feature/*

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Parse terraform-config.yml
        id: parse_config
        run: |
          if command -v yq &> /dev/null; then
            DESTROY_VALUE=$(yq e '.destroy' terraform-config.yml)
          else
            DESTROY_VALUE=$(grep '^destroy:' terraform-config.yml | awk '{print $2}')
          fi
          echo "Valor lido de destroy: $DESTROY_VALUE"
          echo "DESTROY=$DESTROY_VALUE" >> $GITHUB_ENV

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6

      - name: Ensure S3 Backend Exists
        run: |
          BUCKET_NAME="terraform-state-bucket-devair"
          REGION="us-east-2"
          if ! aws s3api head-bucket --bucket "$BUCKET_NAME" 2>/dev/null; then
            echo "Bucket does not exist. Creating..."
            aws s3api create-bucket --bucket "$BUCKET_NAME" --region "$REGION" \
              --create-bucket-configuration LocationConstraint="$REGION"
            echo "Bucket created: $BUCKET_NAME"
          else
            echo "Bucket already exists: $BUCKET_NAME"
          fi
          aws s3api put-bucket-versioning --bucket "$BUCKET_NAME" \
            --versioning-configuration Status=Enabled

      - name: Terraform Init with Remote State
        run: |
          terraform init \
            -backend-config="bucket=terraform-state-bucket-devair" \
            -backend-config="key=terraform.tfstate" \
            -backend-config="region=us-east-2"

      - name: Terraform Plan
        env:
          WHATSAPP_TOKEN: ${{ secrets.WHATSAPP_TOKEN }}
          VERIFY_TOKEN: ${{ secrets.VERIFY_TOKEN }}
        run: terraform plan \
          -var whatsapp_token=${{ secrets.WHATSAPP_TOKEN }} \
          -var verify_token=${{ secrets.VERIFY_TOKEN }}

      - name: Terraform Apply
        if: ${{ env.DESTROY != 'true' }}
        env:
          WHATSAPP_TOKEN: ${{ secrets.WHATSAPP_TOKEN }}
          VERIFY_TOKEN: ${{ secrets.VERIFY_TOKEN }}
        run: terraform apply -auto-approve \
          -var whatsapp_token=${{ secrets.WHATSAPP_TOKEN }} \
          -var verify_token=${{ secrets.VERIFY_TOKEN }}

      - name: Terraform Destroy
        if: ${{ env.DESTROY == 'true' }}
        env:
          WHATSAPP_TOKEN: ${{ secrets.WHATSAPP_TOKEN }}
          VERIFY_TOKEN: ${{ secrets.VERIFY_TOKEN }}
        run: terraform destroy -auto-approve \
          -var whatsapp_token=${{ secrets.WHATSAPP_TOKEN }} \
          -var verify_token=${{ secrets.VERIFY_TOKEN }}
